### ISSUE TITLE
Exception when get metas from i18nResource

### ISSUE THREAD

**Issue by Kiennh** [qor/admin#106]
hi
My program
```
package main

import (
        "fmt"
        "net/http"

        "github.com/jinzhu/gorm"
        _ "github.com/jinzhu/gorm/dialects/mysql"
        _ "github.com/jinzhu/gorm/dialects/postgres"
        _ "github.com/mattn/go-sqlite3"

        "github.com/qor/admin"
        "github.com/qor/qor"

        "github.com/qor/i18n"
        "github.com/qor/i18n/backends/database"
        "github.com/qor/i18n/backends/yaml"
)

type User struct {
        gorm.Model
        Name      string
        Product   Product
        ProductID uint
}

// Create another GORM-backend model
type Product struct {
        gorm.Model
        Name        string
        Description string
}

func main() {
        DB, err := gorm.Open("postgres", fmt.Sprintf("postgres://%v:%v@%v/%v?sslmode=disable", "*", "*", "*", "*"))
        if err != nil {
                fmt.Println(err)
                return
        }
        defer DB.Close()
        DB.AutoMigrate(&User{}, &Product{})
        // Initalize
        Admin := admin.New(&qor.Config{DB: DB})
        Admin.I18n = i18n.New(database.New(DB), yaml.New("config/locales"))
        i18nResource := Admin.AddResource(Admin.I18n, &admin.Config{Invisible: true})
        if i18nResource != nil {
                fmt.Println("hit")
                for _, meta := range i18nResource.GetMetas([]string{}) {
                        fmt.Println("meta", meta.GetName())
                }
        }
        // Create resources from GORM-backend model
        user := Admin.AddResource(&User{})
        product := Admin.AddResource(&Product{})
        product.IndexAttrs("ID", "Name", "Description")
        product.EditAttrs("ID", "Name", "Description")
        user.Meta(&admin.Meta{Name: "Product",
                Config: &admin.SelectOneConfig{SelectMode: "bottom_sheet", RemoteDataResource: product},
        })
        // Register route

        mux := http.NewServeMux()
        // amount to /admin, so visit `/admin` to view the admin interface
        Admin.MountTo("/admin", mux)
        fmt.Println("started")
        http.ListenAndServe(":9000", mux)
}
```

The exception is:
```
hit
panic: reflect: call of reflect.Value.FieldByName on zero Value

goroutine 1 [running]:
reflect.flag.mustBe(0x0, 0x19)
        /usr/local/go/src/reflect/value.go:201 +0xae
reflect.Value.FieldByName(0x0, 0x0, 0x0, 0x970b16, 0x4, 0x0, 0xc42048e820, 0x196)
        /usr/local/go/src/reflect/value.go:812 +0x49
github.com/jinzhu/gorm.(*Scope).Fields(0xc420798280, 0xc420798280, 0xf4b120, 0xa63940)
        /home/kien/go/src/github.com/jinzhu/gorm/scope.go:119 +0x1c3
github.com/qor/admin.(*Resource).configure(0xc42048e9c0)
        /home/kien/go/src/github.com/qor/admin/resource.go:739 +0x141
github.com/qor/admin.(*Resource).NewResource(0xc42048e340, 0xa74000, 0xc42048e820, 0x0, 0x0, 0x0, 0x0)
        /home/kien/go/src/github.com/qor/admin/resource.go:150 +0xdc
github.com/qor/admin.(*Meta).configure(0xc420789ba0)
        /home/kien/go/src/github.com/qor/admin/meta.go:268 +0x86f
github.com/qor/admin.(*Resource).GetMetas(0xc42048e340, 0xc420643cc0, 0x3, 0x0, 0x0, 0x0, 0xc42048e340)
        /home/kien/go/src/github.com/qor/admin/resource.go:656 +0x75b
main.main()
        /home/kien/go/src/qor-test/main.go:49 +0x67e
```

**Comment by jinzhu** [comment]
I18n resource is special, it is not a normal CRUD Resource, it overrides all routes and handles requests by itself, so you can't get metas from it, do you have any reason to get it?

**Comment by Kiennh** [comment]
I have some scenario which filter to every meta of each resource to set permission or allow user config style by themselves. It's worked (Sorry i don't remember the commit hash), but some recent versions of qor admin, i crash when i filter to I18n resource or Worker resource.
