### ISSUE TITLE
丢服务器上测试Admin template 资源打包的问题？

### ISSUE THREAD

**Issue by conku** [qor/admin#168]
Listening on: 9000
2019/01/01 21:23:39 Finish [GET] /admin Took 0.00ms
2019/01/01 21:23:39 http: panic serving [::1]:5565: runtime error: invalid memor
y address or nil pointer dereference
goroutine 22 [running]:
net/http.(*conn).serve.func1(0x128886c0)
        /usr/local/go/src/net/http/server.go:1726 +0x9f
panic(0x8005e0, 0xad20a8)
        /usr/local/go/src/runtime/panic.go:502 +0x1d0
html/template.(*Template).escape(0x0, 0x0, 0x0)
        /usr/local/go/src/html/template/template.go:95 +0x2d
html/template.(*Template).Execute(0x0, 0x8e83e0, 0x12b29e60, 0x854c20, 0x12a9e70
0, 0x1, 0x12b5e060)
        /usr/local/go/src/html/template/template.go:119 +0x21
        /usr/local/go/src/net/http/server.go:2337 +0xf0
net/http.serverHandler.ServeHTTP(0x12a67b00, 0x8ea440, 0x12b29e60, 0x12a67b80)
        /usr/local/go/src/net/http/server.go:2694 +0x98
net/http.(*conn).serve(0x128886c0, 0x8ea700, 0x1290f360)
        /usr/local/go/src/net/http/server.go:1830 +0x5dd
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x1f6

**Comment by cnrowei** [comment]
request couldn't find the template file, maybe you can try to new a dir in your binary, named app/views/qor, copy github.com/qor/admin/views/* to the new dir.

> Listening on: 9000
> 2019/01/01 21:23:39 Finish [GET] /admin Took 0.00ms
> 2019/01/01 21:23:39 http: panic serving [::1]:5565: runtime error: invalid memor
> y address or nil pointer dereference
> goroutine 22 [running]:
> net/http.(*conn).serve.func1(0x128886c0)
> /usr/local/go/src/net/http/server.go:1726 +0x9f
> panic(0x8005e0, 0xad20a8)
> /usr/local/go/src/runtime/panic.go:502 +0x1d0
> html/template.(*Template).escape(0x0, 0x0, 0x0)
> /usr/local/go/src/html/template/template.go:95 +0x2d
> html/template.(*Template).Execute(0x0, 0x8e83e0, 0x12b29e60, 0x854c20, 0x12a9e70
> 0, 0x1, 0x12b5e060)
> /usr/local/go/src/html/template/template.go:119 +0x21
> /usr/local/go/src/net/http/server.go:2337 +0xf0
> net/http.serverHandler.ServeHTTP(0x12a67b00, 0x8ea440, 0x12b29e60, 0x12a67b80)
> /usr/local/go/src/net/http/server.go:2694 +0x98
> net/http.(*conn).serve(0x128886c0, 0x8ea700, 0x1290f360)
> /usr/local/go/src/net/http/server.go:1830 +0x5dd
> created by net/http.(*Server).Serve
> /usr/local/go/src/net/http/server.go:2795 +0x1f6
request couldn't find the template file, maybe you can try to new a dir in your binary, named app/views/qor, copy github.com/qor/admin/views/* to the new dir.
