### ISSUE TITLE
Example raises an error

### ISSUE THREAD

**Issue by marceloboeira** [qor/admin#173]
When trying to run the example on REAME.md I get this:

```
Listening on: 9000
2019/01/22 14:39:09 Finish [GET] / Took 0.08ms
2019/01/22 14:39:09 http: panic serving [::1]:63480: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc0000ba460)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x460aba0, 0x4ac0b60)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0x4747780, 0xc000284c40, 0x468b920, 0xc0000e69a0, 0x1, 0xc0003667e0)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:119 +0x2f
github.com/foo/go/vendor/github.com/qor/admin.(*Context).Execute(0xc0000e69a0, 0x46922be, 0x9, 0x0, 0x0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/context.go:227 +0x244
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard(0xc00052a150, 0xc0000e69a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/controller.go:28 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard-fm(0xc0000e69a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:143 +0x34
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func2(0xc0000e69a0, 0xc0000b25e0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:176 +0xe2
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x4692cf3, 0xa, 0xc00052a250, 0xc0000b25e0, 0xc0000e69a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func1(0xc0000e69a0, 0xc0000b25a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:166 +0xa1
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x469d0b2, 0x1c, 0x46d5c00, 0xc0000b25a0, 0xc0000e69a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc0000e69a0, 0xc0000b2560)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/composite_primary_key_callback.go:27 +0x204
github.com/foo/go/vendor/github.com/qor/admin.(*serveMux).ServeHTTP(0xc000484158, 0x474b020, 0xc000284c40, 0xc000166000)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:267 +0x556
net/http.(*ServeMux).ServeHTTP(0xc00026a570, 0x474b020, 0xc000284c40, 0xc000166000)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00009a0d0, 0x474b020, 0xc000284c40, 0xc000166000)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000ba460, 0x474b3a0, 0xc0004fc500)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2019/01/22 14:39:09 Finish [GET] / Took 0.06ms
2019/01/22 14:39:09 http: panic serving [::1]:63481: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc0000e3900)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x460aba0, 0x4ac0b60)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0x4747780, 0xc000284ee0, 0x468b920, 0xc0000e7030, 0x1, 0xc000366840)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:119 +0x2f
github.com/foo/go/vendor/github.com/qor/admin.(*Context).Execute(0xc0000e7030, 0x46922be, 0x9, 0x0, 0x0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/context.go:227 +0x244
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard(0xc00052a150, 0xc0000e7030)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/controller.go:28 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard-fm(0xc0000e7030)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:143 +0x34
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func2(0xc0000e7030, 0xc0000b25e0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:176 +0xe2
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x4692cf3, 0xa, 0xc00052a250, 0xc0000b25e0, 0xc0000e7030)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func1(0xc0000e7030, 0xc0000b25a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:166 +0xa1
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x469d0b2, 0x1c, 0x46d5c00, 0xc0000b25a0, 0xc0000e7030)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc0000e7030, 0xc0000b2560)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/composite_primary_key_callback.go:27 +0x204
github.com/foo/go/vendor/github.com/qor/admin.(*serveMux).ServeHTTP(0xc000484158, 0x474b020, 0xc000284ee0, 0xc000166100)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:267 +0x556
net/http.(*ServeMux).ServeHTTP(0xc00026a570, 0x474b020, 0xc000284ee0, 0xc000166100)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00009a0d0, 0x474b020, 0xc000284ee0, 0xc000166100)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000e3900, 0x474b3a0, 0xc0004fc700)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5
2019/01/22 14:39:09 Finish [GET] / Took 0.05ms
2019/01/22 14:39:09 http: panic serving [::1]:63482: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc0000e3f40)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1746 +0xd0
panic(0x460aba0, 0x4ac0b60)
	/usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:513 +0x1b9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:95 +0x2e
html/template.(*Template).Execute(0x0, 0x4747780, 0xc000285180, 0x468b920, 0xc0000e7810, 0x1, 0xc0003668a0)
	/usr/local/Cellar/go/1.11/libexec/src/html/template/template.go:119 +0x2f
github.com/foo/go/vendor/github.com/qor/admin.(*Context).Execute(0xc0000e7810, 0x46922be, 0x9, 0x0, 0x0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/context.go:227 +0x244
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard(0xc00052a150, 0xc0000e7810)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/controller.go:28 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Controller).Dashboard-fm(0xc0000e7810)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:143 +0x34
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func2(0xc0000e7810, 0xc0000b25e0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:176 +0xe2
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x4692cf3, 0xa, 0xc00052a250, 0xc0000b25e0, 0xc0000e7810)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.(*Admin).NewServeMux.func1(0xc0000e7810, 0xc0000b25a0)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:166 +0xa1
github.com/foo/go/vendor/github.com/qor/admin.Middleware.Next(0x469d0b2, 0x1c, 0x46d5c00, 0xc0000b25a0, 0xc0000e7810)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:37 +0x48
github.com/foo/go/vendor/github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc0000e7810, 0xc0000b2560)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/composite_primary_key_callback.go:27 +0x204
github.com/foo/go/vendor/github.com/qor/admin.(*serveMux).ServeHTTP(0xc000484158, 0x474b020, 0xc000285180, 0xc000166200)
	/Users/bar/go/src/github.com/foo/go/vendor/github.com/qor/admin/route.go:267 +0x556
net/http.(*ServeMux).ServeHTTP(0xc00026a570, 0x474b020, 0xc000285180, 0xc000166200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc00009a0d0, 0x474b020, 0xc000285180, 0xc000166200)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000e3f40, 0x474b3a0, 0xc0004fc800)
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:2851 +0x2f5

```

**Comment by thanateros** [comment]
Same here.  Started fresh with `qor-example` and this is what I get when I try to go to the admin page right after spinning it up.

**Comment by marceloboeira** [comment]
I kinda gave up, looks like the project is abandoned. The whole dependency management is already a joke in Go, then the project doesn't use tag releases, so you have to point to master, too flaky for me.

**Comment by trevex** [comment]
I don't think the project is abandoned, this is obviously a bug... Is there a sensible solution to this?

I am using go v1.12.7 and the new module system. I tried both master and explicitly downgraded to `v1.1` commits, without success. And both results in the above stacktrace.

Is there a specific version requirment on GORM?

**Comment by harikt** [comment]
@marceloboeira I wonder why you closed this. Can you provide a way to fix this ?

I am also looking at the example code.

```
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"github.com/qor/admin"
	_ "github.com/qor/qor"
	"net/http"
)

// Define a GORM-backend model
type User struct {
	gorm.Model
	Name string
}

// Define another GORM-backend model
type Product struct {
	gorm.Model
	Name string
	Description string
}

func main() {
	// Set up the database
	DB, _ := gorm.Open("sqlite3", "demo.db")
	DB.AutoMigrate(&User{}, &Product{})
	// Initalize
	Admin := admin.New(&admin.AdminConfig{DB: DB})
	// Create resources from GORM-backend model
	Admin.AddResource(&User{})
	Admin.AddResource(&Product{})
	// Initalize an HTTP request multiplexer
	mux := http.NewServeMux()
	// Mount admin to the mux
	Admin.MountTo("/admin", mux)
	fmt.Println("Listening on: 9000")
	http.ListenAndServe(":9000", mux)
}
```

It produces error as 

```
[2020-02-28 12:10:15] [info] registering callback `qor_admin:composite_primary_key` from /projects/go/src/github.com/qor/admin/composite_primary_key_callback.go:34  

[2020-02-28 12:10:15] [info] registering callback `qor_admin:composite_primary_key` from /projects/go/src/github.com/qor/admin/composite_primary_key_callback.go:39
Listening on: 9000
```

and quits.
