### ISSUE TITLE
net/http.(*Server).Serve error

### ISSUE THREAD

**Issue by x0rzkov** [qor/admin#210]
Hi guys,

Hope you are all well !

I try to run qor-admin from a docker container, and it is triggering a weird error from net/http package.

ref. https://github.com/x0rzkov/oniontree

```bash
docker-compose up
```

gives me the following error
```bash
oniontree_1  | 2019/12/14 15:54:43 http: panic serving 172.19.0.3:35988: runtime error: invalid memory address or nil pointer dereference
oniontree_1  | goroutine 1022 [running]:
oniontree_1  | net/http.(*conn).serve.func1(0xc000152140)
oniontree_1  | 	/usr/local/go/src/net/http/server.go:1767 +0x139
oniontree_1  | panic(0xa52400, 0xf83e20)
oniontree_1  | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
oniontree_1  | html/template.(*Template).escape(0x0, 0x0, 0x0)
oniontree_1  | 	/usr/local/go/src/html/template/template.go:95 +0x42
oniontree_1  | html/template.(*Template).Execute(0x0, 0xbe44a0, 0xc000410000, 0xaebd40, 0xc000174000, 0x1, 0xc00009a090)
oniontree_1  | 	/usr/local/go/src/html/template/template.go:119 +0x2f
oniontree_1  | github.com/qor/admin.(*Context).Execute(0xc000174000, 0xaf396d, 0x9, 0x0, 0x0)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/context.go:227 +0x22c
oniontree_1  | github.com/qor/admin.(*Controller).Dashboard(...)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/controller.go:28
oniontree_1  | github.com/qor/admin.(*Admin).NewServeMux.func2(0xc000174000, 0xc0003ce3e0)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/route.go:176 +0x1e6
oniontree_1  | github.com/qor/admin.Middleware.Next(...)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/route.go:37
oniontree_1  | github.com/qor/admin.(*Admin).NewServeMux.func1(0xc000174000, 0xc0003ce3c0)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/route.go:166 +0x115
oniontree_1  | github.com/qor/admin.Middleware.Next(...)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/route.go:37
oniontree_1  | github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc000174000, 0xc000440700)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/composite_primary_key_callback.go:27 +0x24d
oniontree_1  | github.com/qor/admin.(*serveMux).ServeHTTP(0xc0000a0668, 0xbee3a0, 0xc000410000, 0xc000462100)
oniontree_1  | 	/go/pkg/mod/github.com/qor/admin@v0.0.0-20191211090149-7b936172cf06/route.go:267 +0x559
oniontree_1  | net/http.(*ServeMux).ServeHTTP(0xc000392a80, 0xbee3a0, 0xc000410000, 0xc000462100)
oniontree_1  | 	/usr/local/go/src/net/http/server.go:2387 +0x1bd
oniontree_1  | net/http.serverHandler.ServeHTTP(0xc0004101c0, 0xbee3a0, 0xc000410000, 0xc000462100)
oniontree_1  | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
oniontree_1  | net/http.(*conn).serve(0xc000152140, 0xbefaa0, 0xc00044a0c0)
oniontree_1  | 	/usr/local/go/src/net/http/server.go:1890 +0x875
oniontree_1  | created by net/http.(*Server).Serve
oniontree_1  | 	/usr/local/go/src/net/http/server.go:2928 +0x384
```

Does anyone know what is happening ?

Cheers,
X

**Comment by sergolius** [comment]
@x0rzkov out of box qor admin is not compatible with go modules.
The error occurred because template was not found.
https://github.com/qor/auth/issues/23#issuecomment-569522292

Accordingly to https://doc.getqor.com simples solution is to compile templates into binary via https://github.com/qor/bindatafs

**Comment by x0rzkov** [comment]
Would be awesome to have a gist or repo with an example running bindatafs and qor admin.

**Comment by sergolius** [comment]
@x0rzkov just follow https://doc.getqor.com/guides/bindatafs.html and dive into source code 

repo: https://github.com/sergolius/qor_bindatafs_example
I tried to commit step by step

**Comment by x0rzkov** [comment]
awesome, thank you very much !

**Comment by x0rzkov** [comment]
@sergolius , hope you are all well !

I was just wondering if you have any idea how to sort another issue I posted https://github.com/qor/auth/issues/42

I am locked and need to find at least some hints about how to do it ^^.
