### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by joe-at-startupmedia** [qor/admin#87]
I have to following:

```golang

package main

import (
  "fmt"
  "net/http"

  "github.com/qor/admin"
  "github.com/qor/qor"

  "provider-golang-admin/db"
)

func main() {

  Admin := admin.New(&qor.Config{DB: db.DB})

  Admin.SetSiteName("Provider Admin Portal")

    // Register route
  mux := http.NewServeMux()
  // amount to /admin, so visit `/admin` to view the admin interface
  Admin.MountTo("/admin", mux)

  fmt.Println("Listening on: 9000")
  http.ListenAndServe(":9000", mux)
}
```

When I visit admin I get this:

```bash
[git@startup-staging-web provider-golang-admin]$ go run main.go
Listening on: 9000
2017/07/31 11:57:15 Finish [GET] /admin Took 0.28ms
2017/07/31 11:57:15 http: panic serving 108.188.37.234:51916: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc420077900)
	/usr/lib/golang/src/net/http/server.go:1721 +0xd0
panic(0x9920e0, 0xcf04b0)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/lib/golang/src/html/template/template.go:94 +0x38
html/template.(*Template).Execute(0x0, 0xcc4700, 0xc4200ca460, 0xa1e700, 0xc42044a620, 0x1, 0xc420445c20)
	/usr/lib/golang/src/html/template/template.go:117 +0x2f
github.com/qor/admin.(*Context).Execute(0xc42044a620, 0xa26c3f, 0x9, 0x0, 0x0)
	/home/git/go/src/github.com/qor/admin/context.go:214 +0x2a8
github.com/qor/admin.(*Controller).Dashboard(0xc420467e60, 0xc42044a620)
	/home/git/go/src/github.com/qor/admin/controller.go:28 +0x52
github.com/qor/admin.(*Controller).Dashboard-fm(0xc42044a620)
	/home/git/go/src/github.com/qor/admin/route.go:143 +0x34
github.com/qor/admin.(*Admin).NewServeMux.func2(0xc42044a620, 0xc4200f5b00)
	/home/git/go/src/github.com/qor/admin/route.go:176 +0xe0
github.com/qor/admin.Middleware.Next(0xa27b36, 0xa, 0xc420467f40, 0xc4200f5b00, 0xc42044a620)
	/home/git/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.(*Admin).NewServeMux.func1(0xc42044a620, 0xc4200f5ac0)
	/home/git/go/src/github.com/qor/admin/route.go:166 +0xb5
github.com/qor/admin.Middleware.Next(0xa3574e, 0x1c, 0xa6e038, 0xc4200f5ac0, 0xc42044a620)
	/home/git/go/src/github.com/qor/admin/route.go:37 +0x48
github.com/qor/admin.Admin.registerCompositePrimaryKeyCallback.func1(0xc42044a620, 0xc4200f4b00)
	/home/git/go/src/github.com/qor/admin/composite_primary_key_callback.go:27 +0x1a3
github.com/qor/admin.(*serveMux).ServeHTTP(0xc42000e7f8, 0xcc9bc0, 0xc4200ca460, 0xc4200e0100)
	/home/git/go/src/github.com/qor/admin/route.go:399 +0x518
net/http.(*ServeMux).ServeHTTP(0xc420444570, 0xcc9bc0, 0xc4200ca460, 0xc4200e0100)
	/usr/lib/golang/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420084c60, 0xcc9bc0, 0xc4200ca460, 0xc4200e0100)
	/usr/lib/golang/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420077900, 0xcca3c0, 0xc420174b80)
	/usr/lib/golang/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2668 +0x2ce
```

Go Version
```
go version go1.8.3 linux/amd64
```

**Comment by joe-at-startupmedia** [comment]
Closing, duplicate of #56
